# Generated by Django 5.0.6 on 2024-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='address',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(blank=True, choices=[('Westerstede', 'Westerstede')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='zip_code',
            field=models.CharField(blank=True, choices=[('26655', '26655')], max_length=5, null=True),
        ),
    ]
