# Generated by Django 5.0.6 on 2024-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='city',
            field=models.CharField(choices=[('Westerstede', 'Westerstede')], default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='house_number',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(default='123', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='street',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='zip_code',
            field=models.CharField(choices=[('26655', '26655')], default='26655', max_length=5),
            preserve_default=False,
        ),
    ]
