# Generated by Django 5.0.6 on 2024-07-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('g', 'g'), ('unit', 'unit')], max_length=10)),
                ('category', models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('slug', models.SlugField(unique=True)),
                ('allow_half_units', models.BooleanField(default=False, help_text='Allow half units for this product')),
            ],
        ),
    ]
