# Generated by Django 5.0.6 on 2024-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='2024 02 2', unique=True),
            preserve_default=False,
        ),
    ]
