# Generated by Django 5.0.6 on 2024-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_half_units',
            field=models.BooleanField(default=False, help_text='Allow half units for this product'),
        ),
    ]
