# Generated by Django 5.0.6 on 2024-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
